import {createSlice} from "@reduxjs/toolkit";

// Default initial state
const initialState = {
    detailsForm: {

        //address
        keyCode: "",
        searchAddress: "",
        addressLine1: "",
        addressLine2: "",
        searchSuburborPoscode: "",
        suburb: "",
        state: "",
        postCode: "",
        postalAddress: "",
        contactPreference: "",

        // general details
        placeOfBirth: "",
        dateOfBirth: "",
        age: "",
        maritalStatus: "",
        employmentStatus: "",
        fax: "",
        livingCircumstances: "",
        interpreterRequired: "",
        assistiveTechnology: "",
        auslan: "",
        binary: "",
        ttl: "",
        otherCommunicationAssistance: "",
        lgbtiqa: "",
        cald: "",
        aboriginal: "",
        torresStraitIslander: "",
        aboriginalAndTorresStraitIslander: "",
        otherIdentities: "",
        satss: "",
        englishSpeaking: "",
        otherLanguages: "",
        acmps: "",
        sparc: "",
        clientNumber: "",
        pensionNumber: "",
        medicareNumber: "",
        ambulanceNumber: "",
        dvaNumber: "",
        trn: "",
        wsm: "",
        reh: "",
        macReferralCode: "",
        myAgedCareNumber: "",
        privateHealth: "",
        companionCard: "",
        healthCareCard: "",
        religion: "",
        spiritualWellbeing: "",
        caregiverRoutine: "",

        // comments
        comments: "",

        //financial and legal status
        financialAndLegalStatus: "",
        legalOrders: "",
        vulnerableToFinancial: "",

        // Service Status
        clientType: "",
        enquiryDate: "",
        enquiryMinutes: "",
        serviceStatus: "",
        auditOptOut: "",
        covidServiceStatus: "",
        serviceStart: "",
        lastReviewDate: "",
        serviceReviewDatePrimary: "",
        serviceReviewDateSecondary: "",
        serviceEnd: "",
        reasonServiceEnded: "",
        auditorName: "",
        auditDate: "",

        // referral
        referral: "",
        referrer: "",
        referringAgency: "",
        referralDate: "",

        // work health and safety
        workHealthAndSafetyCheck: "",
        ohsNote: "",
        safetyDevice: "",
        vulnerableToFire: "",
        vulnerableToPowerOutage: "",
        vulnerableToFloods: "",
        vulnerableToSevereWeatherEvents: "",
        receivingSupportFromOneWorkerOnly: "",
        livingAlone: "",
        livingInRuralOrRemoteRegionWithLimitedServiceOptions: "",
        sociallyIsolatedOrLackCloseRelationships: "",
        fewOrNoFamilyOrFriendsWhoCheckInOnThem: "",
        cognitiveImpairmentAndAreUnableToProblemSolveOrSpeakUp: "",
        communicationDifficulties: "",
        limitedMobility: "",
        highlyDependentOnTheirCaregiver: "",
        requiresDailyPersonalSelfCareActivities: "",
        carerStatus: "",

        // billing details
        billingPreference: "",
        billingName: "",
        billingAddressLine1: "",
        billingAddressLine2: "",
        billingSuburb: "",
        billingState: "",
        billingPostCode: "",
        billingEmail: "",
        billingPhone1: "",
        billingPhone2: "",

        // finance - credit card
        creditCardNumber: "",
        creditExpiryDate: "",
        creditCardType: "",
        creditCardName: "",

        // health
        covidVaccine1: "",
        covidVaccine2: "",
        boosterVaccine: "",
        covidExemption: "",
        inIsolation: "",
        isolationStartDate: "",
        isolationEndDate: "",
        weight: "",
        height: "",
        includeProsthesis: "",
        amputationLevel: "",
        ampLeft: "",
        ampRight: "",
        complexNeeds: "",
        visionImpaired: "",
        hearingImpaired: "",
        speechImpaired: "",
        needsIndicator: "",
        diagonasedDisability: "",
        undiagnosedDisability: "",
        disabilitySupportPension: "",
        primaryDisablity: "",
        secondaryDisablity: "",
        associatedDisablity: "",
        associatedMedicalConditions: "",
        mobilityLevel: "",
        manualHandlingRequired: "",
        mobility: "",
        transponderNo: "",
        dementiaAndCognitiveImpairment: "",
        vulnerableClient: "",
        vulnerableStateRegistered: "",
        vulnerableToHeat: "",
        vulnerableReason: "",
        managementPlan: "",
        typeOfManagementPlan: "",
        medicationAdministration: "",
        medicationPrompt: "",
        selfAdministered: "",
        medication: "",
        DiagnosisAndPMHX: "",
        oxygenSupport: "",
        mealtimeManagement: "",
        mealtimeManagementNote: "",
        allergy: "",
        resusStatus: "",
        promotingIndependence: "",
        swallowingProblem: "",
        assistanceRequired: "",
        assistanceRequiredDescription: "",
        dietType: "",
        feedingAidsRequired: "",
        fluidType: "",
        thickened: "",
        thickenedLevel: "",
        preferredContinence: "",
        preferredContinenceDescription: "",
        stomaBag: "",
        catheter: "",
        suprapubic: "",
        plainScore: "",
        whatRelievesPain: "",
        whatMakesPainWorse: "",
        sleepReview: "",
        skinIntegrity: "",
        bradenScaleScore: "",
        otherRelevantHealthInformation: "",

        // alerts
        alertNote: "",
        popupInProfile: "",
        rosterNote: "",
        popupInRoster: "",

        // client profile vWorker
        clientProfile: "",
        accesstoResidencyNotes: "",
        identifiedRisks: "",
        livingArrangements: "",
        shiftAlert: "",

    },
};

const detailsSlice = createSlice({
    name: "clientdetails",
    initialState: initialState,
    reducers: {
        upsertData: (state, action) => {
            state.detailsForm = {...action.payload};
        },
        deleteData: (state) => {
            state.detailsForm = initialState.detailsForm;
        },
    },
});

export const {upsertData, deleteData} = detailsSlice.actions;
export default detailsSlice.reducer;


